# Generated by Django 2.0.2 on 2019-12-21 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_host', models.CharField(blank=True, default='', max_length=64, verbose_name='来源')),
                ('type', models.CharField(choices=[('url_illegal_redirect', 'URL非法重定向')], default='', max_length=64, verbose_name='类型')),
                ('path', models.CharField(default='online', max_length=255, verbose_name='path')),
                ('full_path', models.CharField(default='online', max_length=255, verbose_name='full_path')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
