# Generated by Django 2.0.2 on 2019-12-21 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, default='', max_length=64, verbose_name='payload')),
                ('type', models.CharField(choices=[('xss', 'XSS')], default='', max_length=64, verbose_name='类型')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
